CTD-400 handle provisioning file with multiple passwords (#72)
* Revert "CTD-418-add updated changelog"
Dealing with merge issues.  Will update changelog later.
This reverts commit ec7429dedd0cafc5093e51cc5d5c56482dc1eaab.

* CTD-400 handle bulk provisioning file with multiple passwords.

diff --git a/connectd/usr/bin/connectd_library b/connectd/usr/bin/connectd_library
--- a/connectd/usr/bin/connectd_library
+++ b/connectd/usr/bin/connectd_library
@@ -9,9 +9,9 @@
 #  Copyright (C) 2019 remot3.it, Inc. All rights reserved.
 
 ##### Settings #####
-LIBVERSION=lib_v2.1.17
+LIBVERSION=lib_v2.1.18
 AUTHOR="Gary Worsham"
-LIBMODIFIED="April 17, 2019"
+LIBMODIFIED="December 20, 2019"
 GREPFLAGS=
 apikey="remote.it.developertoolsHW9iHnd"
 
@@ -259,7 +259,7 @@ getHardwareID()
             exit 1
         fi
         debug "UID=$deviceaddress"
-        secret=$(grep ^password "$rmt3provFile" | awk '{ print $2 }')
+        secret=$(grep ^password "$rmt3provFile" | tail -n 1 | awk '{ print $2 }')
         if [ "$secret" = "" ]; then
             echo "Bulk Service provisioning file does not have a secret."
             echo "Please contact support@remote.it with this information."
@@ -271,6 +271,11 @@ getHardwareID()
         fi
         result=$(curl ${CURL_OPTS} 'POST' $getHWIDURL -d "{\"deviceaddress\":\"$deviceaddress\", \"secret\":\"$secret\" }" -H "Content-Type:application/json" -H "apikey:$apikey" -H "token:$token")
         HardwareID=$(jsonval "$result" "hardware_id")
+        if [ "$HardwareID" = "" ]; then
+            echo "Error getting Hardware ID from Bulk Service."
+            echo "Please contact support@remote.it with this information."
+            exit 1
+        fi
     else
 	setHardwareID
     fi
